### ISSUE TITLE
Bug: Multi Select

### ISSUE THREAD

**Issue by frodesigns** [carbon-design-system/carbon-web-components#411]
Options with text of average length or more are unreadable due to ellipsis overflow.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! We allow application to set explicit widths of combo box, dropdown and multi select components. That said, would you try:

```css
bx-multi-select {
  width: 20rem;
}
```
